import { Button } from '@/components/ui/button';
import { ArrowRight, Bot, Droplets, Sparkles } from 'lucide-react';
import Link from 'next/link';
import ParticleBackground from './components/shared/particle-background';
import PageHeader from './components/shared/page-header';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

const features = [
  {
    icon: <Sparkles className="w-8 h-8 mb-4 text-primary" />,
    title: 'Mint Unique Entropy Seeds',
    description: 'Use our AI-powered oracle to generate and mint new Entropy Seeds. Each seed is a unique NFT with a verifiable purity score, representing true, on-chain randomness.',
  },
  {
    icon: <Droplets className="w-8 h-8 mb-4 text-primary" />,
    title: 'Burn Seeds for Random Drops',
    description: 'Transmute your Entropy Seeds by "burning" them. This action triggers an AI-driven process to generate a unique, unpredictable digital asset—from rare artifacts to special badges.',
  },
  {
    icon: <Bot className="w-8 h-8 mb-4 text-primary" />,
    title: 'Verifiable AI-Generated Randomness',
    description: 'Our market is built on a foundation of transparency. The randomness for both seed generation and drops is powered by a generative AI, ensuring fairness and unpredictability.',
  },
];


export default function Home() {
  return (
    <div className="relative isolate overflow-hidden">
      <ParticleBackground />
      <div className="container relative z-10 flex min-h-[calc(100vh-5rem)] items-center justify-center py-16">
        <div className="flex flex-col items-center text-center">
          <PageHeader
            title="Harness the Power of AI-Generated Randomness"
            subtitle="Entropy Market is a decentralized application where you can mint, trade, and burn unique NFTs called Entropy Seeds. Each seed is a vessel of pure, verifiable randomness generated by AI."
          />
          <div className="mt-8 flex items-center justify-center gap-4">
            <Button asChild size="lg" className="font-headline">
              <Link href="/mint" prefetch={true}>
                Start Minting <ArrowRight className="ml-2 h-5 w-5" />
              </Link>
            </Button>
            <Button asChild size="lg" variant="outline" className="font-headline">
              <Link href="/market" prefetch={true}>Explore the Market</Link>
            </Button>
          </div>

          <div className="mt-20 w-full max-w-5xl">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {features.map((feature) => (
                <Card key={feature.title} className="glassmorphism text-center flex flex-col items-center">
                  <CardHeader>
                    {feature.icon}
                    <CardTitle className="font-headline text-xl">{feature.title}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-muted-foreground">{feature.description}</p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
